# For bug test, replace the {download_dir} to the absolute directory where the pipeline was downloaded

## filelist
## Two columns for sample names and download_dir of fq files, if paired-end sequenced, the download_dir of two fq files are joint with ';' 
## one sample per row: ID\t${fq1}\t${fq2}\n
filelist:${wd}/filelist

## Working Dir
work_dir: ${wd}/out

## Number of threads for every single step
threads: 4

#Path to graph reference
graph_prefix: GRCh38.
dist_file: ${wd}/ref/CPC.Phase1.GRCh38-minaf.0.1.dist
min_file: ${wd}/ref/CPC.Phase1.GRCh38-minaf.0.1.min
gbz_file: ${wd}/ref/CPC.Phase1.GRCh38-minaf.0.1.gbz
## PanGenie reference vcf
Graph_preprocessed_vcf: ${wd}/ref/cactus_filtered_ids.vcf

#Linear reference genome
ref_name: GRCh38
## No ALT contigs
ref: ${wd}/ref/GRCh38.pure.fa
ref_dict: ${wd}/ref/GRCh38.pure.dict
size_file: ${wd}/ref/chromosome_size.txt

run_deepvariant: '/share/apps/cluster/singularity-3.10.2/bin/singularity exec /share/apps/singularity/deepvariant-1.5.0.sif  /opt/deepvariant/bin/run_deepvariant'
run_glnexus: '/usr/bin/time -v /share/apps/cluster/singularity-3.10.2/bin/singularity exec /share/apps/gene/GLnexus-1.4.1/glnexus-1.4.1.sif glnexus_cli'
run_pangenie: 'PanGenie'
